// Demo articles
// File: scripts/demo-blogs.mjs
//
// Six articles in each of the six categories the blog page filters by, so
// every filter returns a full grid instead of "No articles found".
//
// CATEGORY IDS ARE LOWERCASE AND FIXED. src/components/blog/BlogFilters.jsx
// matches `post.category` against exactly these six ids. An article filed under
// "Nutrition" instead of "nutrition" is invisible on the page -- which is how
// the first batch of seed data disappeared.
//
// Covers come from public/blog-covers/<category>.svg, generated by
// scripts/make-blog-covers.mjs. Set `image` on an article to override it.

const CATEGORIES = ["training", "nutrition", "technology", "wellness", "mindset", "progress"];

/** Compact authoring shape: [title, excerpt, author, readTime, [[heading, body], ...]] */
const ARTICLES = {
  training: [
    [
      "Your easy days are too hard",
      "The most common mistake in amateur endurance training is running every session at the same moderately uncomfortable pace.",
      "Youssef Haddad",
      "6 min read",
      [
        ["The grey zone", "There is a pace that feels productive: hard enough to feel like training, easy enough to sustain. Almost every self-coached runner gravitates to it, and almost every coached runner is pulled away from it. It is too hard to allow recovery and too easy to drive real adaptation, so it delivers neither."],
        ["What easy actually means", "Easy means you can speak in full sentences. For most people starting out that pace feels insultingly slow, and the instinct is to assume it cannot be doing anything. It is building the aerobic base every faster session draws on. Give it six weeks before judging it."],
      ],
    ],
    [
      "The deload week you keep skipping",
      "Planned recovery is not lost training. It is the week where the previous three weeks finally turn into something.",
      "Omar Fathi",
      "5 min read",
      [
        ["Why it feels wrong", "Cutting volume deliberately feels like going backwards, particularly when the weights are still moving. That is exactly when it works best: a deload taken before you need it costs nothing, and one taken after you needed it costs weeks."],
        ["What to cut", "Cut volume, keep intensity. Roughly half the usual sets at close to the usual load keeps the movement patterns sharp while accumulated fatigue drains away. Dropping the weight instead tends to leave you flat rather than fresh."],
      ],
    ],
    [
      "What to expect in your first month of lifting",
      "Rapid progress, sore legs, and numbers that will never move that fast again. A realistic timeline.",
      "Karim Ziani",
      "7 min read",
      [
        ["Weeks one and two", "Almost all early progress is neurological. You are not building much muscle yet; you are learning to recruit what you already have. This is why the numbers climb so quickly, and why that rate is not sustainable."],
        ["Weeks three and four", "Soreness settles, sessions start feeling routine, and the first plateau appears. This is where most people either add a structured programme or quietly stop. Adding structure is the better option."],
      ],
    ],
    [
      "Why your squat stalls at the same weight every time",
      "Hitting the same wall repeatedly is rarely a strength problem. It is usually a programming one.",
      "Amine Belkacem",
      "6 min read",
      [
        ["The repeated month", "Most lifters who stall are running the same four weeks over and over: push hard, get tired, get sick of it, start again. Without a planned progression and a planned back-off, every cycle ends at the same place."],
        ["Fixing it", "Pick a load you can complete comfortably, add a small increment weekly, and cut volume every fourth week. The first fortnight will feel too easy. That is the point -- you are building the runway to exceed your old ceiling rather than crashing into it again."],
      ],
    ],
    [
      "Two days a week is enough to get stronger",
      "The research on training frequency is friendlier to busy people than the internet suggests.",
      "Samira Haddadi",
      "5 min read",
      [
        ["What the evidence says", "When weekly volume is matched, training a muscle twice a week produces very similar results to training it four times. Frequency is a way of distributing volume, not a separate ingredient."],
        ["Making two days work", "Both sessions cover the whole body, built on compound lifts. Squat, press, hinge and pull in each one, with enough sets to accumulate meaningful volume. It is unglamorous and it works."],
      ],
    ],
    [
      "Warm-ups worth the ten minutes",
      "Most warm-ups are either skipped entirely or twenty minutes of stretching that does nothing for the session ahead.",
      "Hakim Saidi",
      "4 min read",
      [
        ["What a warm-up is for", "Raising tissue temperature, rehearsing the movement, and giving the nervous system a preview of the load. Static stretching does the first, badly, and none of the others."],
        ["A workable structure", "Five minutes raising your heart rate, then the movement you are about to do with an empty bar and progressively heavier sets. That is it. Save mobility work for after, or for its own session."],
      ],
    ],
  ],

  nutrition: [
    [
      "How much protein do you actually need?",
      "Between the supplement industry and the internet, the number has drifted a long way from the evidence.",
      "Sara Mansouri",
      "7 min read",
      [
        ["The range that matters", "For people training regularly, the evidence clusters around 1.6 to 2.2 grams per kilogram of bodyweight per day. Below that you leave adaptation on the table. Above it, the extra benefit is hard to measure."],
        ["Practical targets", "A 70kg person training four times a week needs roughly 110 to 150 grams daily. That is achievable with ordinary food: eggs at breakfast, a protein source at lunch and dinner, dairy or legumes filling the gaps. Powder is a convenience, not a requirement."],
      ],
    ],
    [
      "Eating for a morning workout",
      "Training before work raises a question no evening lifter has to answer: eat first, or not?",
      "Yacine Boudiaf",
      "5 min read",
      [
        ["Fasted is fine, mostly", "For a session under an hour at moderate intensity, training fasted is unlikely to cost you anything. Above that, or for anything genuinely hard, performance usually drops."],
        ["If you do eat", "Something small and mostly carbohydrate, thirty to sixty minutes before. A banana, toast and honey, a small bowl of oats. Fat and fibre slow digestion, which is useful at breakfast and unhelpful before a squat session."],
      ],
    ],
    [
      "The supplements you can stop buying",
      "Most consultations end with a shorter shopping list than the client arrived with.",
      "Zakaria Hamdi",
      "6 min read",
      [
        ["The short list that works", "Creatine monohydrate, caffeine, and vitamin D if you are deficient. Protein powder counts as food rather than a supplement. That list is unexciting because it is the part with actual evidence behind it."],
        ["The rest", "Fat burners, BCAAs alongside adequate protein, testosterone boosters, most greens powders. The money is better spent on the food you would otherwise skip, or on a coach."],
      ],
    ],
    [
      "Hitting protein on a plant-based diet",
      "It is entirely doable, and it is where most new vegetarians quietly fall short.",
      "Meriem Chelbi",
      "6 min read",
      [
        ["The gap", "Plant proteins are generally lower in leucine and less digestible, so the practical target sits slightly higher than for omnivores. Aiming for the top of the usual range covers it."],
        ["What to build around", "Lentils, tofu, tempeh, seitan, soy milk and, if you use it, a pea or soy isolate. Spreading protein across the day matters a little more here than it does on an omnivorous diet."],
      ],
    ],
    [
      "Why slow fat loss wins",
      "An aggressive deficit does not just feel worse. It costs you the muscle you were trying to keep.",
      "Othmane Riahi",
      "6 min read",
      [
        ["What speed costs", "Beyond roughly 0.5 to 1 percent of bodyweight per week, an increasing share of what you lose is lean tissue. Training performance falls, which reduces the stimulus telling your body to keep muscle at all."],
        ["The other reason", "Slow deficits are the ones people finish. A twelve-week plan completed beats a six-week plan abandoned in week three, and the second is far more common than the first."],
      ],
    ],
    [
      "Fuelling around Ramadan training",
      "A month of altered eating does not have to be a month of lost progress.",
      "Bassem Trigui",
      "7 min read",
      [
        ["Timing the session", "Training shortly before iftar, or one to two hours after, works best for most people. Before iftar means you can eat and rehydrate immediately; after means you train fed."],
        ["Protecting muscle", "Keep protein high across the eating window and keep training, even at reduced volume. Maintaining strength is a realistic goal for the month; adding to it usually is not, and that is fine."],
      ],
    ],
  ],

  technology: [
    [
      "What a camera can and cannot tell you about your form",
      "Pose estimation is a useful mirror, not a physiotherapist. What joint-angle analysis measures, and where it goes blind.",
      "Amine Belkacem",
      "8 min read",
      [
        ["What it measures", "A pose model finds your joints in the frame and measures the angles between them. For a squat that means hip, knee and ankle: the knee angle tells you how deep you went, delivered instantly, which no human coach can match for frequency."],
        ["What it misses", "It sees a flat, two-dimensional picture. Rotation toward or away from the lens is invisible, so a knee that caves inward or a spine that rounds away from the camera can pass unnoticed. Use it as feedback, not as permission."],
      ],
    ],
    [
      "How pose estimation actually works",
      "Thirty-three points, a neural network, and a surprising amount of geometry.",
      "TrainSight Team",
      "7 min read",
      [
        ["From pixels to joints", "The model takes a frame and returns coordinates for thirty-three landmarks: shoulders, elbows, wrists, hips, knees, ankles and the rest. Each carries a visibility score, an estimate of how confident it is that the point is actually there."],
        ["From joints to feedback", "Everything after that is trigonometry. Three points make an angle, an angle compared against a range makes a verdict, and a sequence of angles makes a repetition. The clever part is the model; the useful part is the arithmetic."],
      ],
    ],
    [
      "Running the model in your browser, not on our servers",
      "Why form analysis here never uploads a single frame, and what that costs us.",
      "TrainSight Team",
      "6 min read",
      [
        ["The obvious design, and its problems", "The first version sent a frame to a server five times a second. It worked on a laptop and fell apart in deployment: somewhere to host it, bandwidth for every frame, and visible lag between the movement and the skeleton drawn over it."],
        ["Moving it to the edge", "The model now runs in the browser as WebAssembly. Nothing is uploaded, there is no server to keep awake, and the overlay tracks the picture because there is no round trip. The trade is that your device does the work, so an old phone will run it slower."],
      ],
    ],
    [
      "Why your smartwatch calorie count is wrong",
      "Not slightly wrong. Studies routinely find errors of twenty to ninety percent.",
      "TrainSight Team",
      "5 min read",
      [
        ["What it is actually doing", "Your watch measures heart rate and movement, then applies a population-level model adjusted by the height, weight and age you typed in. It has no way to measure the thing it reports."],
        ["Using it anyway", "Treat the number as a consistent-ish index rather than a measurement. Comparing this week to last week on the same device is reasonable. Eating back the calories it reports is not."],
      ],
    ],
    [
      "Heart-rate zones, and what they miss",
      "Zones are a useful shorthand built on an equation that was never meant to be precise.",
      "Selma Gharbi",
      "6 min read",
      [
        ["The 220 minus age problem", "That formula has a standard deviation of roughly ten to twelve beats. Your real maximum could be fifteen beats either side of the estimate, which is enough to shift every zone boundary."],
        ["A better anchor", "Effort-based zones, or a tested threshold, beat an estimated maximum. If you only have the watch, use it for trends rather than for deciding whether a session was the right intensity."],
      ],
    ],
    [
      "Rep counting is harder than it looks",
      "Counting to ten is trivial. Counting to ten from a noisy stream of joint coordinates is not.",
      "TrainSight Team",
      "6 min read",
      [
        ["The naive version", "Watch an angle, count each time it dips below a threshold. It works until someone pauses at the bottom, or shakes, or the model loses a knee for two frames -- then one rep becomes four."],
        ["What actually works", "A state machine with hysteresis: the rep only counts when the angle passes a low threshold, and only re-arms after it passes a separate high one. Two thresholds instead of one, and the flicker disappears."],
      ],
    ],
  ],

  wellness: [
    [
      "Undoing desk shoulders in fifteen minutes a day",
      "Eight hours at a keyboard does predictable things to a thoracic spine. The fix is unglamorous and it works.",
      "Inès Bouraoui",
      "6 min read",
      [
        ["The pattern", "Rounded upper back, shoulders drawn forward, neck compensating for both. It is not a moral failing to be fixed by sitting up straight; it is tissue adapting to the position it spends most of its time in."],
        ["The daily fifteen", "Thoracic extension over a foam roller, shoulder controlled articular rotations, a doorway pec stretch and two minutes of diaphragmatic breathing. Every day, before training rather than after."],
      ],
    ],
    [
      "Sleep is the training variable you control least",
      "And the one with the largest effect on everything else you are trying to do.",
      "Leila Nouri",
      "6 min read",
      [
        ["What it costs", "Restricting sleep reduces strength output, slows recovery, raises perceived effort and pushes appetite toward more food and worse choices. No supplement compensates for it."],
        ["The boring interventions", "A consistent wake time, a dark cool room, and caffeine finished by early afternoon. They sound trivial next to a training programme and they move the needle further."],
      ],
    ],
    [
      "Breathing drills that actually calm you down",
      "Most breathing advice is vague. The mechanism is not.",
      "Khalil Ouali",
      "5 min read",
      [
        ["Why the exhale matters", "Heart rate rises slightly on the inhale and falls on the exhale. Lengthening the exhale relative to the inhale nudges the system toward the parasympathetic side. That is the entire trick."],
        ["One drill", "Four counts in through the nose, six to eight out through the mouth, for two minutes. It is not mystical and it does not require a class."],
      ],
    ],
    [
      "Training when you are stressed",
      "Stress does not pause because you have a programme, and training through it needs adjusting rather than abandoning.",
      "Mariam Zouaoui",
      "5 min read",
      [
        ["Recovery is systemic", "Your body does not keep separate accounts for work deadlines and heavy squats. A stressful month means less capacity for training stress, not the same capacity plus willpower."],
        ["What to change", "Keep the frequency, cut the volume. Turning up for a shorter easier session preserves the habit, and the habit is what survives the month."],
      ],
    ],
    [
      "The case for walking",
      "The least fashionable form of exercise remains the one most people should do more of.",
      "Dounia Ferhat",
      "4 min read",
      [
        ["Why it works", "It is sustainable, it barely interferes with recovery, it is available without equipment or a change of clothes, and it accumulates. Nothing else in the list is true of interval training."],
        ["A realistic target", "Adding two thousand steps to your current daily average is a better goal than ten thousand from a standing start, because you will still be doing it in March."],
      ],
    ],
    [
      "Rest days are not days off",
      "The adaptation you are training for happens between sessions, not during them.",
      "Ilyes Guedri",
      "5 min read",
      [
        ["What actually happens", "Training is the stimulus; the repair afterwards is the adaptation. Skipping rest does not add training, it subtracts recovery and leaves you accumulating fatigue you never convert into progress."],
        ["Active beats total", "A walk, an easy swim, some mobility work. Movement without meaningful load tends to leave people feeling better than complete inactivity, without eating into recovery."],
      ],
    ],
  ],

  mindset: [
    [
      "Motivation is not the problem",
      "Waiting to feel like training is why most programmes end in February.",
      "Nadia Cherif",
      "5 min read",
      [
        ["Motivation follows action", "It is far easier to act your way into feeling like training than to feel your way into acting. The session you did not want to do is usually indistinguishable from the one you did, twenty minutes in."],
        ["Build for the bad days", "Design your week around what you will do when you feel worst, not best. A plan that only survives high motivation is not a plan, it is a mood."],
      ],
    ],
    [
      "Why you quit in week three",
      "The dropout point is remarkably consistent, and the reason is structural rather than personal.",
      "Karim Ziani",
      "6 min read",
      [
        ["The novelty runs out", "Weeks one and two are carried by enthusiasm and fast beginner progress. By week three the novelty is gone, the progress has slowed, and nothing has replaced either."],
        ["What replaces it", "Something measurable that is not how you look: a weight on a bar, a distance, a number of sessions attended. Progress you can see on a page survives the week the mirror stops cooperating."],
      ],
    ],
    [
      "Training through a plateau",
      "The weights stop moving long before you stop improving.",
      "Amine Belkacem",
      "6 min read",
      [
        ["Plateaus are normal", "Early progress is fast because you start from nothing. The closer you get to your current ceiling, the slower the approach. A stalled month after a year of training is not failure, it is arithmetic."],
        ["What to change", "Change one variable and hold it for six weeks: volume, frequency, or exercise selection. Changing all three at once means learning nothing from the result."],
      ],
    ],
    [
      "Comparison and the gym",
      "Everyone in the room started somewhere, and almost nobody is watching you.",
      "Imen Jaziri",
      "4 min read",
      [
        ["The spotlight you imagine", "People consistently overestimate how much others notice them. In a gym, most people are counting their own reps and looking at their own phone."],
        ["The useful comparison", "Compare yourself to your own log from three months ago. It is the only comparison with matched conditions, and the only one that can tell you anything actionable."],
      ],
    ],
    [
      "How to restart after a long break",
      "Coming back is not the same as starting, and treating it like either extreme goes badly.",
      "Mehdi Khelifi",
      "5 min read",
      [
        ["Muscle memory is real", "Previously trained muscle regains size and strength considerably faster than it took to build. The capacity comes back quickly; the connective tissue and the conditioning lag behind it."],
        ["The trap", "Your nervous system remembers what you used to lift and your tendons do not. Start at roughly half, add back over four to six weeks, and accept that the first fortnight will feel insultingly easy."],
      ],
    ],
    [
      "Discipline is a schedule, not a feeling",
      "The people who train consistently are not the ones who want it more.",
      "Omar Fathi",
      "4 min read",
      [
        ["Decisions are the expensive part", "Deciding whether to train, when, and what to do costs willpower before you have lifted anything. Fixed days and a written plan remove three decisions from every session."],
        ["Lower the bar for showing up", "A rule of never missing twice beats a rule of never missing. The first survives a bad week; the second ends at the first one."],
      ],
    ],
  ],

  progress: [
    [
      "The scale is a bad progress report",
      "Daily bodyweight moves for a dozen reasons, and almost none of them are fat.",
      "Sara Mansouri",
      "5 min read",
      [
        ["What moves the number", "Water, glycogen, sodium, what is still in your digestive tract, and where you are in a menstrual cycle. Day-to-day swings of one to two kilograms are ordinary and say nothing about body composition."],
        ["How to read it", "Weigh under the same conditions and look at a weekly average against the previous weekly average. The trend is signal; any individual morning is noise."],
      ],
    ],
    [
      "How to know if a programme is working",
      "Six weeks in, the honest answer is usually available if you wrote anything down.",
      "Omar Fathi",
      "6 min read",
      [
        ["Pick the metric first", "Decide before you start what improving would look like: load on a lift, reps at a load, a distance, a time. A programme evaluated on how you feel will be judged by how the last session went."],
        ["Give it long enough", "Four to six weeks is the minimum before a strength programme has said anything. Switching at week two guarantees a permanent state of starting over."],
      ],
    ],
    [
      "Tracking without obsessing",
      "Logging your training helps. Logging everything is its own problem.",
      "Lamia Ben Youssef",
      "5 min read",
      [
        ["The minimum useful log", "Exercise, load, sets, reps, and a one-word note on how it felt. That is enough to make every future programming decision. Anything beyond it is optional."],
        ["When to stop", "If the tracking is producing anxiety rather than decisions, it has stopped being a tool. Measuring less often is a legitimate answer."],
      ],
    ],
    [
      "Strength gains slow down, and that is fine",
      "The rate of progress in year three looks nothing like year one, and should not.",
      "Hakim Saidi",
      "5 min read",
      [
        ["The shape of the curve", "A beginner may add weight weekly. An intermediate adds it monthly. An advanced lifter measures progress across a year. Each of those is normal at that stage, and comparing across stages causes a lot of unnecessary discouragement."],
        ["What changes", "Later progress comes from accumulating good years rather than good weeks. Consistency stops being the thing that gets you started and becomes the whole method."],
      ],
    ],
    [
      "Photos, measurements, and the numbers that matter",
      "The mirror is unreliable precisely because you use it every day.",
      "Rania Toumi",
      "5 min read",
      [
        ["Why photos work", "Change is gradual enough to be invisible day to day and obvious across twelve weeks. Same light, same position, same time of day, once a fortnight."],
        ["Measurements as backup", "Waist and hip circumference track composition better than bodyweight does. Take them under the same conditions, and expect them to move slowly."],
      ],
    ],
    [
      "Your first year, realistically",
      "What actually happens across twelve months of consistent training, without the marketing.",
      "Samira Haddadi",
      "7 min read",
      [
        ["Months one to three", "Rapid strength gains that are mostly neurological, noticeable improvements in how movements feel, and relatively little visible change. This is the stretch where expectations and reality diverge most."],
        ["Months four to twelve", "Visible change accumulates, strength gains slow to something steadier, and training stops being an event and becomes a routine. The people who get results in year two are the ones who found year one boring and kept going."],
      ],
    ],
  ],
};

// Cover photographs, chosen per article and keyed by title.
//
// Every id below was checked to return 200 from images.unsplash.com. That is
// the part that can be verified from here; whether a given photo suits its
// headline is a judgement call, so swap any that look wrong -- it is one line,
// and an article with no entry here simply falls back to its category cover.
//
// That fallback is the important part. Hardcoded photo urls have broken twice
// on this site, and a missing entry should cost a nice photo, not the layout.
const PHOTOS = {
  // training -- gym and road
  "Your easy days are too hard": "photo-1461896836934-ffe607ba8211",
  "The deload week you keep skipping": "photo-1517836357463-d25dfeac3438",
  "What to expect in your first month of lifting": "photo-1571019613454-1cb2f99b2d8b",
  "Why your squat stalls at the same weight every time": "photo-1534438327276-14e5300c3a48",
  "Two days a week is enough to get stronger": "photo-1552196563-55cd4e45efb3",
  "Warm-ups worth the ten minutes": "photo-1541534741688-6078c6bfb5c5",

  // nutrition -- food
  "How much protein do you actually need?": "photo-1490645935967-10de6ba17061",
  "Eating for a morning workout": "photo-1517673132405-a56a62b18caf",
  "The supplements you can stop buying": "photo-1498837167922-ddd27525d352",
  "Hitting protein on a plant-based diet": "photo-1547592166-23ac45744acd",
  "Why slow fat loss wins": "photo-1512621776951-a57141f2eefd",
  "Fuelling around Ramadan training": "photo-1490645935967-10de6ba17061",

  // technology -- screens and measurement
  "What a camera can and cannot tell you about your form": "photo-1534438327276-14e5300c3a48",
  "How pose estimation actually works": "photo-1483058712412-4245e9b90334",
  "Running the model in your browser, not on our servers": "photo-1483058712412-4245e9b90334",
  "Why your smartwatch calorie count is wrong": "photo-1579126038374-6064e9370f0f",
  "Heart-rate zones, and what they miss": "photo-1499209974431-9dddcece7f88",
  "Rep counting is harder than it looks": "photo-1550345332-09e3ac987658",

  // wellness -- yoga, breathing, walking
  "Undoing desk shoulders in fifteen minutes a day": "photo-1544367567-0f2fcb009e0b",
  "Sleep is the training variable you control least": "photo-1506126613408-eca07ce68773",
  "Breathing drills that actually calm you down": "photo-1506126613408-eca07ce68773",
  "Training when you are stressed": "photo-1594381898411-846e7d193883",
  "The case for walking": "photo-1476480862126-209bfaa8edc8",
  "Rest days are not days off": "photo-1544367567-0f2fcb009e0b",

  // mindset
  "Motivation is not the problem": "photo-1518611012118-696072aa579a",
  "Why you quit in week three": "photo-1540497077202-7c8a3999166f",
  "Training through a plateau": "photo-1534438327276-14e5300c3a48",
  "Comparison and the gym": "photo-1517836357463-d25dfeac3438",
  "How to restart after a long break": "photo-1499209974431-9dddcece7f88",
  "Discipline is a schedule, not a feeling": "photo-1552196563-55cd4e45efb3",

  // progress
  "The scale is a bad progress report": "photo-1512621776951-a57141f2eefd",
  "How to know if a programme is working": "photo-1541534741688-6078c6bfb5c5",
  "Tracking without obsessing": "photo-1483058712412-4245e9b90334",
  "Strength gains slow down, and that is fine": "photo-1571019613454-1cb2f99b2d8b",
  "Photos, measurements, and the numbers that matter": "photo-1579126038374-6064e9370f0f",
  "Your first year, realistically": "photo-1461896836934-ffe607ba8211",
};

const photoUrl = (id) => `https://images.unsplash.com/${id}?w=1200&h=675&fit=crop`;

const slug = (title) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_|_$/g, "")
    .slice(0, 48);

export const blogs = CATEGORIES.flatMap((category) =>
  ARTICLES[category].map(([title, excerpt, author, readTime, sections]) => ({
    id: `demo_blog_${category}_${slug(title)}`,
    title,
    excerpt,
    author,
    category,
    readTime,
    // A photo where one suits the headline, the category cover otherwise.
    image: PHOTOS[title] ? photoUrl(PHOTOS[title]) : `/blog-covers/${category}.svg`,
    sections: sections.map(([heading, content]) => ({ heading, content })),
  }))
);

export const BLOG_CATEGORIES = CATEGORIES;
